### ISSUE TITLE
Some imagery layers don't work

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#273]
The following example doesn't work:

```
from pywwt.qt import WWTQtClient
%gui qt
wwt = WWTQtClient()
wwt.foreground = wwt.imagery.other.planck2
```

(``wwt.imagery.other.planck2 == 'Planck Spinning Dust'``)

@pkgw - just to check, any ideas why this might be happening?

**Comment by pkgw** [comment]
Ah, right, this issue. So the problem is that the WebGL engine has a somewhat annoying thing where it has an internal list of available image sets loadable via (e.g.) `loadForegroundImageByName`. When you load a new WTML file, its imagesets do **not** necessarily get added to that list. By default the WebGL engine can only load-by-name the imagesets listed in this file:

http://web.wwtassets.org/engine/assets/builtin-image-sets.wtml

That file contains a variety of data sets, including a couple of Planck ones (in terms of sheer numbers, it's dominated by panorama data sets), but not the spinning dust.

Meanwhile the list of surveys in pywwt is derived from:

https://worldwidetelescope.github.io/pywwt/surveys.xml

(which in turn derives from http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=surveys)

which is the "All-Sky Surveys" folder of the default webclient explore view. In pywwt we feed `surveys.xml` into `wwt.loadImageCollection` but it turns out that this does *not* cause the imagesets to be added to the table of nameable imagesets. So then `loadForegroundImageByName` and friends don't work with them.

Possible courses of action:

- Synchronize the pywwt list of images with `builtin-image-sets.wtml`, which is what it should have been all along.
- Make it so that the imagesets in `surveys.xml` actually get registered with the engine so that they are findable.

As a side comment, the existence of `surveys.xml` at all is a bit of an artifact from the times when we had very little control over the WWT web presence. Nowadays we could host such data files on `web.wwtassets.org` or something similar instead of GitHub pages.

**Comment by pkgw** [comment]
Sorry, that wasn't 100% correct.

[As per the docs][licdoc], the `loadImageCollection` call does add the imagesets in the `surveys.xml` file to the internal list ... but only in the top level of the folder. As you might recall, a while ago we changed something in pywwt to recurse into subfolders as well. "Planck Spinning Dust" is in a "Planck" subfolder, which is why it doesn't get loaded.

[licdoc]: https://docs.worldwidetelescope.org/webgl-reference/latest/apiref/engine/classes/scriptinterface.html#loadimagecollection

**Comment by astrofrog** [comment]
Solved by https://github.com/WorldWideTelescope/pywwt/pull/274
