### ISSUE TITLE
TimeoutError both in cloud- and local-based tutorial ipynb

### ISSUE THREAD

**Issue by mbelveder** [WorldWideTelescope/pywwt#327]
Hi!

I got TimeoutError both in cloud- (left part of the screenshot) and local-based (right part) tutorial ipynb. How can I solve this problem?

![image](https://user-images.githubusercontent.com/43069139/159451134-02e30263-ed45-4f55-b61f-f65bccef7269.png)

**Comment by pkgw** [comment]
I think this is easy to solve! Looking at your screenshots, I think that you need to open up the WWT app before running your commands. As the text in the notebook says:

- Go to the "View" menu
- Select "Activate Command Palette"
- Select "AAS WorldWide Telescope"
- *Then* run the Python command

This is a pretty clear usability issue with our integration. I looked into it and I don't think there's any way for the Python code to cause the app to open up automatically when it's invoked ... but we could at least provide an error message with a tip, here. It's a bit tricky because due to the asynchronous way that the components interact, the Python code can't "know" if the app is running as straightforwardly as you might think, but we can still suggest a course of action.

**Comment by mbelveder** [comment]
It helped, thanks!
